import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

import Changelog from '@/components/changelog';
import Navbar from '@/components/Navbar';
import Hero from '@/components/Hero';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Seomind</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Foundation:wght@700&family=Nunito+Sans:wght@600&family=Pacifico&family=Permanent+Marker&family=Raleway:wght@700&family=Rubik+Iso&family=Source+Code+Pro:ital,wght@0,400;0,900;1,500&family=Ubuntu&display=swap" rel="stylesheet" />
      </Head>
      
      <main className="container max-w-5xl mx-auto">
        <Changelog />
        <Navbar />
        <Hero />
      </main>
    </>
  )
}
